/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frame;
import controladores.ControladorObservaciones;
import controladores.ControladorPersonal;
import java.awt.Desktop;
import java.io.IOException;
import java.net.URI;
import javax.swing.JOptionPane;

public class Personal extends javax.swing.JFrame {
    ControladorPersonal controlador = new ControladorPersonal();
    
    public void openInternet(){
        try {
            Desktop.getDesktop().browse(URI.create("www.google.com"));
        } catch (IOException e) {
            JOptionPane.showConfirmDialog(null, e);
        }
    }
    /**
     * Creates new form Login
     */
    public Personal() {
        initComponents();
        this.setLocationRelativeTo(null);
        //controlador.cargarTabla();
        controlador.cargarTablaArchivo();
    }
    
    

    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabelVolver = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jTextFieldBuscar = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableEmpleados = new javax.swing.JTable();
        jLabelReloadTable = new javax.swing.JLabel();
        jLabelVerEmpleado = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_Expand_Arrow_32px.png"))); // NOI18N
        jLabel14.setToolTipText("");
        jLabel14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 10, -1, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_Multiply_32px.png"))); // NOI18N
        jLabel15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 10, -1, -1));

        jLabelVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_Back_32px.png"))); // NOI18N
        jLabelVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelVolverMouseClicked(evt);
            }
        });
        jPanel1.add(jLabelVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 30, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 40));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextFieldBuscar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldBuscar.setForeground(new java.awt.Color(102, 102, 102));
        jTextFieldBuscar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 99, 71)));
        jTextFieldBuscar.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                jTextFieldBuscarComponentAdded(evt);
            }
        });
        jTextFieldBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBuscarActionPerformed(evt);
            }
        });
        jTextFieldBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldBuscarKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldBuscarKeyReleased(evt);
            }
        });
        jPanel2.add(jTextFieldBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 20, 180, 30));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_Search_32px_2.png"))); // NOI18N
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 20, -1, -1));

        jTableEmpleados.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 13)); // NOI18N
        jTableEmpleados.setForeground(new java.awt.Color(51, 51, 51));
        jTableEmpleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Apellidos", "Nombres", "DNI", "Fecha de Nacimiento", "Edad", "Fecha de Ingreso", "Antiguedad", "Afiliado", "Nro de matricula", "Nivel", "Cargo", "Funcion"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableEmpleados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableEmpleadosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableEmpleados);
        if (jTableEmpleados.getColumnModel().getColumnCount() > 0) {
            jTableEmpleados.getColumnModel().getColumn(4).setMinWidth(50);
            jTableEmpleados.getColumnModel().getColumn(4).setPreferredWidth(50);
            jTableEmpleados.getColumnModel().getColumn(4).setMaxWidth(50);
            jTableEmpleados.getColumnModel().getColumn(6).setMinWidth(60);
            jTableEmpleados.getColumnModel().getColumn(6).setPreferredWidth(90);
            jTableEmpleados.getColumnModel().getColumn(6).setMaxWidth(100);
        }

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 1260, 900));

        jLabelReloadTable.setFont(new java.awt.Font("Arial Narrow", 1, 12)); // NOI18N
        jLabelReloadTable.setForeground(new java.awt.Color(255, 255, 255));
        jLabelReloadTable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn_OFF_65x20.png"))); // NOI18N
        jLabelReloadTable.setText("Recargar");
        jLabelReloadTable.setToolTipText("");
        jLabelReloadTable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelReloadTable.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabelReloadTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelReloadTableMouseClicked(evt);
            }
        });
        jPanel2.add(jLabelReloadTable, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        jLabelVerEmpleado.setFont(new java.awt.Font("Arial Narrow", 1, 12)); // NOI18N
        jLabelVerEmpleado.setForeground(new java.awt.Color(255, 255, 255));
        jLabelVerEmpleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn_OFF_65x20.png"))); // NOI18N
        jLabelVerEmpleado.setText("ver empleado");
        jLabelVerEmpleado.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabelVerEmpleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelVerEmpleadoMouseClicked(evt);
            }
        });
        jPanel2.add(jLabelVerEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, -1, 20));

        jLabel1.setFont(new java.awt.Font("Arial Narrow", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn_OFF_65x20.png"))); // NOI18N
        jLabel1.setText("Observaciones");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial Narrow", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/btn_OFF_65x20.png"))); // NOI18N
        jLabel2.setText("Eliminar");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 1280, 980));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBuscarActionPerformed

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        this.setState(ICONIFIED);
    }//GEN-LAST:event_jLabel14MouseClicked

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        int dialog = JOptionPane.YES_NO_OPTION;
        int confirm = JOptionPane.showConfirmDialog(null, "Esta seguro que desea cerrar el programa?","Salir",dialog);
        
        if(confirm == 0){
            System.exit(0);
        }
    }//GEN-LAST:event_jLabel15MouseClicked

    
    private void jLabelReloadTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelReloadTableMouseClicked
        controlador.cargarTablaArchivo();
    }//GEN-LAST:event_jLabelReloadTableMouseClicked

    private void jLabelVolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelVolverMouseClicked
        Prog1 vistaProg = new Prog1();
        vistaProg.setVisible(true);
        hide();
    }//GEN-LAST:event_jLabelVolverMouseClicked

    private void jLabelVerEmpleadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelVerEmpleadoMouseClicked
        controlador.verEmpleadosArchivos();
        hide();
    }//GEN-LAST:event_jLabelVerEmpleadoMouseClicked

    private void jTableEmpleadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableEmpleadosMouseClicked

    }//GEN-LAST:event_jTableEmpleadosMouseClicked

    private void jTextFieldBuscarComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_jTextFieldBuscarComponentAdded

    }//GEN-LAST:event_jTextFieldBuscarComponentAdded

    private void jTextFieldBuscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldBuscarKeyPressed

    }//GEN-LAST:event_jTextFieldBuscarKeyPressed

    private void jTextFieldBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldBuscarKeyReleased
        String date=jTextFieldBuscar.getText();
        controlador.cargarTablaBusquedaArchivo(date);
    }//GEN-LAST:event_jTextFieldBuscarKeyReleased

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        ControladorObservaciones obs = new ControladorObservaciones();
        obs.verObservacionesEmpleadosArchivos();
    }//GEN-LAST:event_jLabel1MouseClicked

    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Personal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Personal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Personal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Personal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Personal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelReloadTable;
    private javax.swing.JLabel jLabelVerEmpleado;
    private javax.swing.JLabel jLabelVolver;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable jTableEmpleados;
    private javax.swing.JTextField jTextFieldBuscar;
    // End of variables declaration//GEN-END:variables
}
